POST http://localhost:3333/motos
Content-Type: application/json

{
    "marca": "Yamaha",
    "cor": "Preta",
    "placa": 379
}

###

GET http://localhost:3333/motos?search=Yamaha

###

GET http://localhost:3333/motos

###

PUT http://localhost:3333/motos/
Content-Type: application/json

{
    "marca": "Yamaha",
    "cor": "Azul",
    "placa": 489
}

###

DELETE http://localhost:3333/motos/