POST http://localhost:3333/moto
Content-Type: application/json

{
    "marca": "Yamaha",
    "cor": "Preta",
    "placa": 379
}

###

GET http://localhost:3333/moto?search=Yamaha

###

GET http://localhost:3333/moto

###

PUT http://localhost:3333/moto/
Content-Type: application/json

{
    "marca": "Yamaha",
    "cor": "Azul",
    "placa": 489
}

###

DELETE http://localhost:3333/moto/
